<?php

use Illuminate\Database\Seeder;
use Elimuswift\DbExporter\SeederHelper;

class MstitemclassDatabaseSeeder extends Seeder 
{

	use SeederHelper;
	
    public function run()
    {
        
        $data = [
            
            [
                'ItemClassId' => '16',
                'ItemClassName' => 'Type',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '1',
                'ParentItemClassId' => '0',
                'FormatPattern' => 'W{W}*H{H}',
                'ItemClassNameVN' => 'Loại',
                'FormatPatternVN' => 'W{W}*H{H}',
                'ItemClassNameJP' => '種類',
                'FormatPatternJP' => 'W{W}*H{H}',
            ],

            [
                'ItemClassId' => '21',
                'ItemClassName' => 'Lock',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '14',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Khóa',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'ロック',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '22',
                'ItemClassName' => 'Door Stoper',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '20',
                'ParentItemClassId' => '16',
                'FormatPattern' => '{Q} sets',
                'ItemClassNameVN' => 'Chặn cửa',
                'FormatPatternVN' => '{Q} Bộ',
                'ItemClassNameJP' => '戸当り',
                'FormatPatternJP' => '{Q} セット',
            ],

            [
                'ItemClassId' => '23',
                'ItemClassName' => 'Door Installation',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa ra vào',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'ドアの取付',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '24',
                'ItemClassName' => 'Door Inland Freight',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa ra vào',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'ドアを輸送',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '25',
                'ItemClassName' => 'Flashing',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '05',
                'DispOrder' => '11',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Tấm chắn nước',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => '水切り',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '26',
                'ItemClassName' => 'Frame Depth Type',
                'Unit' => 'Kind',
                'WInputFlg' => '1',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '14',
                'DispOrder' => '4',
                'ParentItemClassId' => '16',
                'FormatPattern' => '{W}',
                'ItemClassNameVN' => 'Độ dày khung',
                'FormatPatternVN' => '{W}',
                'ItemClassNameJP' => 'フレームの厚さ',
                'FormatPatternJP' => '{W}',
            ],

            [
                'ItemClassId' => '27',
                'ItemClassName' => 'Fire Rated Type',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '04',
                'DispOrder' => '3',
                'ParentItemClassId' => '16',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Chống cháy',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => '防火',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '29',
                'ItemClassName' => 'Under Frame Type',
                'Unit' => null,
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '05',
                'DispOrder' => '5',
                'ParentItemClassId' => '16',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Khung dưới',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => '沓擅',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '30',
                'ItemClassName' => 'Window',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '1',
                'PricePattern' => '12',
                'DispOrder' => '6',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{W}*{H} ({Q} Sets)',
                'ItemClassNameVN' => 'Cửa sổ',
                'FormatPatternVN' => '{W}*{H} ({Q} Bộ)',
                'ItemClassNameJP' => '窓',
                'FormatPatternJP' => '{W}*{H} ({Q} セット)',
            ],

            [
                'ItemClassId' => '31',
                'ItemClassName' => 'Window Glass',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '08',
                'DispOrder' => '7',
                'ParentItemClassId' => '30',
                'FormatPattern' => '{I} ({Q} Sets)',
                'ItemClassNameVN' => 'Kính',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => '窓ガラス',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '32',
                'ItemClassName' => 'Louver',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '1',
                'PricePattern' => '12',
                'DispOrder' => '8',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{W}*{H} ({Q} Sets)',
                'ItemClassNameVN' => 'Lam cửa',
                'FormatPatternVN' => '{W}*{H} ({Q} Bộ)',
                'ItemClassNameJP' => 'ガラリ',
                'FormatPatternJP' => '{W}*{H} ({Q} セット)',
            ],

            [
                'ItemClassId' => '33',
                'ItemClassName' => 'Insect Net',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '18',
                'DispOrder' => '9',
                'ParentItemClassId' => '32',
                'FormatPattern' => '{Q} Sets',
                'ItemClassNameVN' => 'Lưới côn trùng',
                'FormatPatternVN' => '{Q} Bộ',
                'ItemClassNameJP' => 'アミ戸',
                'FormatPatternJP' => '{Q} セット',
            ],

            [
                'ItemClassId' => '34',
                'ItemClassName' => 'Glass Wool',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '02',
                'DispOrder' => '10',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Sợi bông thủy tinh',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'グラスウール',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '35',
                'ItemClassName' => 'Rail Cover',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '05',
                'DispOrder' => '12',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Ốp ray',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'レールカバー',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '36',
                'ItemClassName' => 'Order Color',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '08',
                'DispOrder' => '13',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Màu cửa',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'カラー',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '37',
                'ItemClassName' => 'Master Key',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '09',
                'DispOrder' => '15',
                'ParentItemClassId' => '21',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Khóa chủ',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'マスターキー',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '38',
                'ItemClassName' => 'Hinges Additional',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '13',
                'DispOrder' => '16',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Bản lề phát sinh',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => '追加ヒンジ',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '39',
                'ItemClassName' => 'Handle Type',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '17',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Tay nắm',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'ハンドルタイプ',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '40',
                'ItemClassName' => 'Door Closer',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '18',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Tay co',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'ドアクローザー',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '41',
                'ItemClassName' => 'HardWare',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '19',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Phụ kiện',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => '部品',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '42',
                'ItemClassName' => 'SS Type',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '1',
                'ParentItemClassId' => '0',
                'FormatPattern' => 'W{W}*H{H}',
                'ItemClassNameVN' => 'Loại cửa cuốn',
                'FormatPatternVN' => 'W{W}*H{H}',
                'ItemClassNameJP' => 'SSタイプ',
                'FormatPatternJP' => 'W{W}*H{H}',
            ],

            [
                'ItemClassId' => '43',
                'ItemClassName' => 'Motor',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '5',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Động cơ',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'モーター',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '44',
                'ItemClassName' => 'PBS',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '10',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} Sets)',
                'ItemClassNameVN' => 'Hộp công tắc',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'PBS',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '45',
                'ItemClassName' => 'Case',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '15',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Hộp',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'ケース',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '46',
                'ItemClassName' => 'Wind Proof',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '04',
                'DispOrder' => '20',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Ray chống bão',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => '風防',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '48',
                'ItemClassName' => 'Steel Makeup Flame',
                'Unit' => 'M',
                'WInputFlg' => '1',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '14',
                'DispOrder' => '21',
                'ParentItemClassId' => '60',
                'FormatPattern' => '{W}',
                'ItemClassNameVN' => 'Khung thép trang trí',
                'FormatPatternVN' => '{W}',
                'ItemClassNameJP' => 'スチールメイクフレーム',
                'FormatPatternJP' => '{W}',
            ],

            [
                'ItemClassId' => '49',
                'ItemClassName' => 'Order Color',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '08',
                'DispOrder' => '35',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Màu cửa',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'カラー',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '50',
                'ItemClassName' => 'SUS Rail',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '06',
                'DispOrder' => '40',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Thanh ray I-nox',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'SUSレール',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '51',
                'ItemClassName' => 'SUS Bottom Bar',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '05',
                'DispOrder' => '45',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Thanh đáy I-nox',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'ステレス　ボトム',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '52',
                'ItemClassName' => 'Auto Closing Device',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '09',
                'DispOrder' => '50',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Thiết bị đóng tự động',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => '自動閉鎖装置',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '53',
                'ItemClassName' => 'SS Installation',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '42',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa cuốn',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'SS取付',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '54',
                'ItemClassName' => 'SS Inland Freight',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '42',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa cuốn',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'SS輸送',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '55',
                'ItemClassName' => 'Bottom Rubber',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '05',
                'DispOrder' => '25',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Thanh đáy cao su',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'ボトムゴム',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '59',
                'ItemClassName' => 'QS Type(M2)',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '1',
                'ParentItemClassId' => '0',
                'FormatPattern' => 'W{W}*H{H}',
                'ItemClassNameVN' => 'Loại cửa cuốn nhanh (Mini)',
                'FormatPatternVN' => 'W{W}*H{H}',
                'ItemClassNameJP' => 'QSタイプ（M2)',
                'FormatPatternJP' => 'W{W}*H{H}',
            ],

            [
                'ItemClassId' => '61',
                'ItemClassName' => 'Sensor',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '5',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} Sets)',
                'ItemClassNameVN' => 'Cảm ứng',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'センサー',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '62',
                'ItemClassName' => 'Vision Pane',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '10',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} Sets)',
                'ItemClassNameVN' => 'Ô lấy sáng',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => '明かり窓',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '63',
                'ItemClassName' => 'SUS Rail Cover',
                'Unit' => 'M',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '1',
                'PricePattern' => '06',
                'DispOrder' => '15',
                'ParentItemClassId' => '60',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Ốp ray I-nox',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'ステレス　レールカバ',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '64',
                'ItemClassName' => 'Steel Makeup Flame',
                'Unit' => 'M',
                'WInputFlg' => '1',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '14',
                'DispOrder' => '20',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{W}',
                'ItemClassNameVN' => 'Khung thép trang trí',
                'FormatPatternVN' => '{W}',
                'ItemClassNameJP' => 'スチールメイクフレーム',
                'FormatPatternJP' => '{W}',
            ],

            [
                'ItemClassId' => '65',
                'ItemClassName' => 'Transformer',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '25',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I} ({Q} Sets)',
                'ItemClassNameVN' => 'Máy biến áp',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'トランス',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '66',
                'ItemClassName' => 'QS Installation(M2)',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '59',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa cuốn nhanh (M2)',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS取付 (M2)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '67',
                'ItemClassName' => 'QS Inland Freight(M2)',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '59',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa cuốn nhanh (M2)',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS輸送 (M2)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '68',
                'ItemClassName' => 'QS Installation(Mini)',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '0',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa cuốn nhanh (Mini) ',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS取付 (Mini)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '69',
                'ItemClassName' => 'QS Inland Freight(Mini)',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '60',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa cuốn nhanh (Mini)',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS輸送 (Mini)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '70',
                'ItemClassName' => 'Sealing',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '15',
                'DispOrder' => '7',
                'ParentItemClassId' => '30',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Silicon',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'シーリング',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '72',
                'ItemClassName' => 'sealing',
                'Unit' => null,
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '1',
                'PricePattern' => '15',
                'DispOrder' => '990',
                'ParentItemClassId' => '0',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'silicon',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'シーリング',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '73',
                'ItemClassName' => 'SUS Case',
                'Unit' => 'M',
                'WInputFlg' => '1',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '05',
                'DispOrder' => '22',
                'ParentItemClassId' => '60',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Hộp I-nox',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'SUSケース',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '74',
                'ItemClassName' => 'Open Frame',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '14',
                'DispOrder' => '13',
                'ParentItemClassId' => '16',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Khung mở rộng',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'オープンフレーム',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '75',
                'ItemClassName' => 'SUS Kick-Plate',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '05',
                'DispOrder' => '13',
                'ParentItemClassId' => '16',
                'FormatPattern' => '{I} ({Q} sets)',
                'ItemClassNameVN' => 'Tấm bảo vệ I-nox',
                'FormatPatternVN' => '{I} ({Q} Bộ)',
                'ItemClassNameJP' => 'SUSのキックプレート',
                'FormatPatternJP' => '{I} ({Q} セット)',
            ],

            [
                'ItemClassId' => '76',
                'ItemClassName' => 'Optional Devices-1',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '23',
                'ParentItemClassId' => '59',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Thiết bị tự chọn - 1',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'オプションのデバイス-1',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '77',
                'ItemClassName' => 'Optional Devices-2',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '24',
                'ParentItemClassId' => '59',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Thiết bị tự chọn - 2',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'オプションのデバイス-2',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '78',
                'ItemClassName' => 'Safety Sensor',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '11',
                'ParentItemClassId' => '42',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Cảm ứng an toàn',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => '安全センサー',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '84',
                'ItemClassName' => 'QS Type(BEAD)',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '1',
                'ParentItemClassId' => '0',
                'FormatPattern' => 'W{W}*H{H}',
                'ItemClassNameVN' => 'Loại cửa cuốn nhanh đầu bi',
                'FormatPatternVN' => 'W{W}*H{H}',
                'ItemClassNameJP' => 'QSタイプ（Bead)',
                'FormatPatternJP' => 'W{W}*H{H}',
            ],

            [
                'ItemClassId' => '85',
                'ItemClassName' => 'QS Installation(BEAD)',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '0',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa cuốn nhanh đầu bi',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS取付 (Bead)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '86',
                'ItemClassName' => 'QS Inland Freight(BEAD)',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '84',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa cuốn nhanh đầu bi',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS輸送 (BEAD)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '87',
                'ItemClassName' => 'QS Type(D310)',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '1',
                'ParentItemClassId' => '0',
                'FormatPattern' => 'W{W}*H{H}',
                'ItemClassNameVN' => 'Loại cửa cuốn nhanh (D310)',
                'FormatPatternVN' => 'W{W}*H{H}',
                'ItemClassNameJP' => 'QSタイプ（310)',
                'FormatPatternJP' => 'W{W}*H{H}',
            ],

            [
                'ItemClassId' => '88',
                'ItemClassName' => 'QS Installation(D310)',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '0',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa cuốn nhanh (D310)',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS取付 (310)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '89',
                'ItemClassName' => 'QS Inland Freight(D310)',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '87',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa cuốn nhanh (D310)',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'QS輸送 (310)',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '90',
                'ItemClassName' => 'Panel',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '1',
                'ParentItemClassId' => '0',
                'FormatPattern' => 'W{W}*H{H}',
                'ItemClassNameVN' => 'Panel',
                'FormatPatternVN' => 'W{W}*H{H}',
                'ItemClassNameJP' => 'パネル',
                'FormatPatternJP' => 'W{W}*H{H}',
            ],

            [
                'ItemClassId' => '92',
                'ItemClassName' => 'Door louver',
                'Unit' => 'M2',
                'WInputFlg' => '1',
                'HInputFlg' => '1',
                'QInputFlg' => '0',
                'PricePattern' => '12',
                'DispOrder' => '2',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{W}*{H} ({Q} Sets)',
                'ItemClassNameVN' => 'Lam cửa',
                'FormatPatternVN' => '{W}*{H} ({Q} Bộ)',
                'ItemClassNameJP' => 'ガラリ',
                'FormatPatternJP' => '{W}*{H} ({Q} セット)',
            ],

            [
                'ItemClassId' => '93',
                'ItemClassName' => 'Panel Installation',
                'Unit' => 'M2',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '10',
                'DispOrder' => '998',
                'ParentItemClassId' => '90',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Lắp đặt cửa Panel',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'Panel取付',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '94',
                'ItemClassName' => 'Panel Inland Freight',
                'Unit' => '%',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '11',
                'DispOrder' => '999',
                'ParentItemClassId' => '90',
                'FormatPattern' => null,
                'ItemClassNameVN' => 'Vận chuyển cửa Panel',
                'FormatPatternVN' => null,
                'ItemClassNameJP' => 'Panel輸送',
                'FormatPatternJP' => null,
            ],

            [
                'ItemClassId' => '95',
                'ItemClassName' => 'Roller Chain',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '6',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Dây xích truyền động',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'ローラーチｴーン',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '96',
                'ItemClassName' => 'Sprocket',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '09',
                'DispOrder' => '7',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Đĩa xích',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'スプロケット梱包',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '97',
                'ItemClassName' => 'Chain option',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '09',
                'DispOrder' => '7',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Dây xích kéo',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'チｴーンオプション梱包',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '98',
                'ItemClassName' => 'Special Rail',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '06',
                'DispOrder' => '40',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Ray đặc biệt',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => '特殊レール',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '99',
                'ItemClassName' => 'ALU Bottom bar',
                'Unit' => 'M',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '0',
                'PricePattern' => '05',
                'DispOrder' => '45',
                'ParentItemClassId' => '42',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Thanh đáy nhôm',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'アルミ ボトム',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '100',
                'ItemClassName' => 'Cere Card Transmitter',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '46',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Bộ phát tín hiệu',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'セレカード送信機',
                'FormatPatternJP' => '{I}',
            ],

            [
                'ItemClassId' => '101',
                'ItemClassName' => 'Cere Card Receiver',
                'Unit' => 'Kind',
                'WInputFlg' => '0',
                'HInputFlg' => '0',
                'QInputFlg' => '1',
                'PricePattern' => '09',
                'DispOrder' => '47',
                'ParentItemClassId' => '0',
                'FormatPattern' => '{I}',
                'ItemClassNameVN' => 'Bộ nhận tín hiệu',
                'FormatPatternVN' => '{I}',
                'ItemClassNameJP' => 'セレカード受信機',
                'FormatPatternJP' => '{I}',
            ],

        ];

        foreach($data as $item) 
        {
            $this->saveData("mstitemclass", $item);
        }
    }

}