<?php

use Illuminate\Database\Seeder;
use Elimuswift\DbExporter\SeederHelper;

class StatusDatabaseSeeder extends Seeder 
{

	use SeederHelper;
	
    public function run()
    {
        
        $data = [
            
            [
                'id' => '19',
                'module_id' => '17',
                'color' => '#FFFFFF',
                'bg' => '#00CE68',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '2',
                'level' => '1',
                'not_select' => '2',
                'options' => '2',
                'status_id' => '1',
                'created_at' => '2019-05-02 08:32:52',
                'updated_at' => '2019-06-21 01:29:12',
            ],

            [
                'id' => '23',
                'module_id' => '17',
                'color' => '#FFFFFF',
                'bg' => '#FFAF00',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-05-02 08:35:08',
                'updated_at' => '2019-06-21 01:27:03',
            ],

            [
                'id' => '24',
                'module_id' => '17',
                'color' => '#FFFFFF',
                'bg' => '#DF0302',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '4',
                'level' => '1',
                'not_select' => '2',
                'options' => '4',
                'status_id' => '1',
                'created_at' => '2019-05-02 08:37:50',
                'updated_at' => '2019-06-21 02:25:24',
            ],

            [
                'id' => '25',
                'module_id' => null,
                'color' => '#FFFFFF',
                'bg' => '#00A850',
                'class_name' => null,
                'is_common' => '1',
                'sort' => '0',
                'level' => '1',
                'not_select' => '0',
                'options' => null,
                'status_id' => '1',
                'created_at' => '2019-05-02 10:49:42',
                'updated_at' => '2019-05-03 11:39:08',
            ],

            [
                'id' => '26',
                'module_id' => null,
                'color' => '#FFFFFF',
                'bg' => '#530303',
                'class_name' => null,
                'is_common' => '1',
                'sort' => '1',
                'level' => '-1',
                'not_select' => '0',
                'options' => null,
                'status_id' => '1',
                'created_at' => '2019-05-02 10:50:43',
                'updated_at' => '2019-05-04 09:11:56',
            ],

            [
                'id' => '32',
                'module_id' => '17',
                'color' => '#FFFFFF',
                'bg' => '#4F0B0B',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-07 09:46:14',
                'updated_at' => '2019-06-10 10:23:11',
            ],

            [
                'id' => '33',
                'module_id' => '17',
                'color' => '#FFFFFF',
                'bg' => '#082EA6',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '3',
                'level' => '1',
                'not_select' => '1',
                'options' => '3',
                'status_id' => '1',
                'created_at' => '2019-06-10 08:38:57',
                'updated_at' => '2019-06-21 01:29:20',
            ],

            [
                'id' => '36',
                'module_id' => '14',
                'color' => '#FFFFFF',
                'bg' => '#4F0B0B',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:15:57',
                'updated_at' => '2019-06-10 10:23:04',
            ],

            [
                'id' => '37',
                'module_id' => '14',
                'color' => '#FFFFFF',
                'bg' => '#FFAF00',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:24:31',
                'updated_at' => '2019-06-21 09:36:55',
            ],

            [
                'id' => '38',
                'module_id' => '14',
                'color' => '#FFFFFF',
                'bg' => '#00CE68',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '2',
                'level' => '1',
                'not_select' => '2',
                'options' => '2',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:25:28',
                'updated_at' => '2019-06-21 09:37:15',
            ],

            [
                'id' => '39',
                'module_id' => '14',
                'color' => '#FFFFFF',
                'bg' => '#082EA6',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '3',
                'level' => '1',
                'not_select' => '1',
                'options' => '3',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:26:42',
                'updated_at' => '2019-06-21 09:37:20',
            ],

            [
                'id' => '40',
                'module_id' => '14',
                'color' => '#FFFFFF',
                'bg' => '#DF0302',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '6',
                'level' => '1',
                'not_select' => '2',
                'options' => '6',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:28:17',
                'updated_at' => '2019-07-15 02:41:01',
            ],

            [
                'id' => '41',
                'module_id' => '14',
                'color' => '#000000',
                'bg' => '#8A8181',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '4',
                'level' => '1',
                'not_select' => '1',
                'options' => '4',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:30:24',
                'updated_at' => '2019-06-21 09:37:32',
            ],

            [
                'id' => '42',
                'module_id' => '14',
                'color' => '#FDE500',
                'bg' => '#0EE118',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '5',
                'level' => '1',
                'not_select' => '1',
                'options' => '5',
                'status_id' => '1',
                'created_at' => '2019-06-10 10:31:47',
                'updated_at' => '2019-07-15 02:40:52',
            ],

            [
                'id' => '43',
                'module_id' => '13',
                'color' => '#FFFFFF',
                'bg' => '#4F0B0B',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-12 07:57:41',
                'updated_at' => '2019-06-12 07:57:41',
            ],

            [
                'id' => '44',
                'module_id' => '13',
                'color' => '#FFFFFF',
                'bg' => '#00CE68',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-06-12 08:16:14',
                'updated_at' => '2019-06-12 08:16:14',
            ],

            [
                'id' => '45',
                'module_id' => '18',
                'color' => '#FFFFFF',
                'bg' => '#00903E',
                'class_name' => null,
                'is_common' => '1',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-06-19 10:01:20',
                'updated_at' => '2019-06-19 10:03:12',
            ],

            [
                'id' => '46',
                'module_id' => '18',
                'color' => '#FFFFFF',
                'bg' => '#590404',
                'class_name' => null,
                'is_common' => '1',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-19 10:02:46',
                'updated_at' => '2019-06-19 10:03:27',
            ],

            [
                'id' => '47',
                'module_id' => '9',
                'color' => '#FFFFFF',
                'bg' => '#00903E',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-06-26 03:37:36',
                'updated_at' => '2019-06-26 03:37:36',
            ],

            [
                'id' => '48',
                'module_id' => '9',
                'color' => '#FFFFFF',
                'bg' => '#590404',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-26 03:38:37',
                'updated_at' => '2019-06-26 03:38:37',
            ],

            [
                'id' => '49',
                'module_id' => '12',
                'color' => '#FFFFFF',
                'bg' => '#00903E',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-06-26 08:50:00',
                'updated_at' => '2019-06-26 08:50:00',
            ],

            [
                'id' => '50',
                'module_id' => '12',
                'color' => '#FFFFFF',
                'bg' => '#590404',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-26 08:50:46',
                'updated_at' => '2019-06-26 08:50:46',
            ],

            [
                'id' => '51',
                'module_id' => '59',
                'color' => '#FFFFFF',
                'bg' => '#00903E',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '0',
                'level' => '1',
                'not_select' => '2',
                'options' => '1',
                'status_id' => '1',
                'created_at' => '2019-06-26 08:51:36',
                'updated_at' => '2019-06-26 08:51:36',
            ],

            [
                'id' => '52',
                'module_id' => '59',
                'color' => '#FFFFFF',
                'bg' => '#590404',
                'class_name' => null,
                'is_common' => '2',
                'sort' => '1',
                'level' => '1',
                'not_select' => '2',
                'options' => '0',
                'status_id' => '1',
                'created_at' => '2019-06-26 08:52:47',
                'updated_at' => '2019-06-26 08:52:47',
            ],

        ];

        foreach($data as $item) 
        {
            $this->saveData("status", $item);
        }
    }

}