<?php

use Illuminate\Database\Seeder;
use Elimuswift\DbExporter\SeederHelper;

class MenusDatabaseSeeder extends Seeder 
{

	use SeederHelper;
	
    public function run()
    {
        
        $data = [
            
            [
                'id' => '2',
                'pid' => '0',
                'path' => '/',
                'class_name' => null,
                'path_id' => '/0/2/',
                'icon' => 'mdi mdi-television',
                'sort' => '2',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '2',
                'created_at' => '2019-04-11 07:45:40',
                'updated_at' => '2019-06-27 03:30:20',
            ],

            [
                'id' => '9',
                'pid' => '10',
                'path' => 'users',
                'class_name' => null,
                'path_id' => '/0/10/9/',
                'icon' => null,
                'sort' => '63',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '11',
                'created_at' => '2019-04-11 07:58:28',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '10',
                'pid' => '0',
                'path' => '/',
                'class_name' => null,
                'path_id' => '/0/10/',
                'icon' => 'mdi mdi-settings',
                'sort' => '46',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '16',
                'created_at' => '2019-04-11 08:10:48',
                'updated_at' => '2019-07-26 08:57:56',
            ],

            [
                'id' => '32',
                'pid' => '10',
                'path' => 'modules',
                'class_name' => null,
                'path_id' => '/0/10/32/',
                'icon' => null,
                'sort' => '67',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '1',
                'created_at' => '2019-04-11 09:07:13',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '33',
                'pid' => '10',
                'path' => 'roles',
                'class_name' => null,
                'path_id' => '/0/10/33/',
                'icon' => null,
                'sort' => '69',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '5',
                'created_at' => '2019-04-11 09:08:10',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '34',
                'pid' => '10',
                'path' => 'languages',
                'class_name' => null,
                'path_id' => '/0/10/34/',
                'icon' => null,
                'sort' => '71',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '6',
                'created_at' => '2019-04-11 09:09:14',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '35',
                'pid' => '10',
                'path' => '/menus',
                'class_name' => null,
                'path_id' => '/0/10/35/',
                'icon' => null,
                'sort' => '75',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '7',
                'created_at' => '2019-04-12 04:49:00',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '37',
                'pid' => '10',
                'path' => 'language-labels',
                'class_name' => null,
                'path_id' => '/0/10/37/',
                'icon' => null,
                'sort' => '73',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '9',
                'created_at' => '2019-04-12 08:22:43',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '38',
                'pid' => '0',
                'path' => 'profile',
                'class_name' => null,
                'path_id' => '/0/38/',
                'icon' => null,
                'sort' => '2',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '4',
                'allow_type' => null,
                'module_id' => '10',
                'created_at' => '2019-04-20 08:26:16',
                'updated_at' => '2019-07-16 07:38:51',
            ],

            [
                'id' => '39',
                'pid' => '0',
                'path' => 'profile/change-password',
                'class_name' => null,
                'path_id' => '/0/39/',
                'icon' => null,
                'sort' => '4',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '4',
                'allow_type' => null,
                'module_id' => '10',
                'created_at' => '2019-04-20 08:26:49',
                'updated_at' => '2019-07-16 07:38:51',
            ],

            [
                'id' => '40',
                'pid' => '0',
                'path' => 'profile/inbox',
                'class_name' => null,
                'path_id' => '/0/40/',
                'icon' => null,
                'sort' => '6',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '4',
                'allow_type' => null,
                'module_id' => '10',
                'created_at' => '2019-04-20 08:27:18',
                'updated_at' => '2019-07-16 07:38:51',
            ],

            [
                'id' => '41',
                'pid' => '0',
                'path' => 'profile/logout',
                'class_name' => null,
                'path_id' => '/0/41/',
                'icon' => null,
                'sort' => '8',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '4',
                'allow_type' => null,
                'module_id' => '10',
                'created_at' => '2019-04-20 08:27:54',
                'updated_at' => '2019-07-16 07:38:51',
            ],

            [
                'id' => '43',
                'pid' => '62',
                'path' => 'customers',
                'class_name' => null,
                'path_id' => '/0/62/43/',
                'icon' => null,
                'sort' => '37',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '12',
                'created_at' => '2019-04-22 11:15:06',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '44',
                'pid' => '62',
                'path' => 'customers/create',
                'class_name' => null,
                'path_id' => '/0/62/44/',
                'icon' => null,
                'sort' => '39',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '12',
                'created_at' => '2019-04-22 11:15:36',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '45',
                'pid' => '0',
                'path' => '#',
                'class_name' => 'Contracts',
                'path_id' => '/0/45/',
                'icon' => null,
                'sort' => '0',
                'level' => '0',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => null,
                'allow_type' => null,
                'module_id' => null,
                'created_at' => '2019-04-22 11:43:22',
                'updated_at' => '2019-04-23 05:16:34',
            ],

            [
                'id' => '46',
                'pid' => '0',
                'path' => '/contracts',
                'class_name' => 'Contracts',
                'path_id' => '/0/46/',
                'icon' => 'mdi mdi-city',
                'sort' => '18',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '13',
                'created_at' => '2019-04-22 11:44:03',
                'updated_at' => '2019-07-03 03:27:10',
            ],

            [
                'id' => '47',
                'pid' => '46',
                'path' => 'contracts',
                'class_name' => null,
                'path_id' => '/0/46/47/',
                'icon' => null,
                'sort' => '19',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '13',
                'created_at' => '2019-04-22 11:44:39',
                'updated_at' => '2019-07-03 03:27:11',
            ],

            [
                'id' => '49',
                'pid' => '0',
                'path' => '#',
                'class_name' => null,
                'path_id' => '/0/49/',
                'icon' => 'mdi mdi-alarm',
                'sort' => '12',
                'level' => '1',
                'description' => null,
                'shortcode' => 'OrderMenusStatus',
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '14',
                'created_at' => '2019-04-23 03:27:03',
                'updated_at' => '2019-07-03 03:27:10',
            ],

            [
                'id' => '50',
                'pid' => '0',
                'path' => 'orders',
                'class_name' => 'orders',
                'path_id' => null,
                'icon' => null,
                'sort' => '0',
                'level' => '0',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => null,
                'allow_type' => null,
                'module_id' => null,
                'created_at' => '2019-04-23 03:43:37',
                'updated_at' => '2019-04-23 03:43:37',
            ],

            [
                'id' => '51',
                'pid' => '49',
                'path' => 'orders',
                'class_name' => 'orders',
                'path_id' => '/0/49/51/',
                'icon' => null,
                'sort' => '13',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '14',
                'created_at' => '2019-04-23 03:44:13',
                'updated_at' => '2019-07-03 03:27:10',
            ],

            [
                'id' => '52',
                'pid' => '49',
                'path' => 'orders/create',
                'class_name' => null,
                'path_id' => '/0/49/52/',
                'icon' => null,
                'sort' => '15',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '14',
                'created_at' => '2019-04-23 03:44:40',
                'updated_at' => '2019-07-03 03:27:10',
            ],

            [
                'id' => '53',
                'pid' => '0',
                'path' => '#',
                'class_name' => 'quotations',
                'path_id' => '/0/53/',
                'icon' => 'mdi mdi-book-open-variant',
                'sort' => '6',
                'level' => '1',
                'description' => null,
                'shortcode' => 'QuotationsMenusStatus',
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '17',
                'created_at' => '2019-04-23 09:17:46',
                'updated_at' => '2019-07-16 09:37:58',
            ],

            [
                'id' => '54',
                'pid' => '53',
                'path' => 'quotations',
                'class_name' => null,
                'path_id' => '/0/53/54/',
                'icon' => null,
                'sort' => '7',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '17',
                'created_at' => '2019-04-23 09:18:38',
                'updated_at' => '2019-07-16 09:37:58',
            ],

            [
                'id' => '55',
                'pid' => '53',
                'path' => 'quotations/create',
                'class_name' => null,
                'path_id' => '/0/53/55/',
                'icon' => null,
                'sort' => '9',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '17',
                'created_at' => '2019-04-23 09:19:16',
                'updated_at' => '2019-07-16 09:37:58',
            ],

            [
                'id' => '57',
                'pid' => '10',
                'path' => 'status',
                'class_name' => null,
                'path_id' => '/0/10/57/',
                'icon' => null,
                'sort' => '65',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '18',
                'created_at' => '2019-05-02 08:00:59',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '58',
                'pid' => '10',
                'path' => '/web-configs',
                'class_name' => null,
                'path_id' => '/0/10/58/',
                'icon' => null,
                'sort' => '81',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '30',
                'created_at' => '2019-05-21 09:11:47',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '62',
                'pid' => '0',
                'path' => '#',
                'class_name' => null,
                'path_id' => '/0/62/',
                'icon' => 'mdi mdi-bank',
                'sort' => '32',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '40',
                'created_at' => '2019-06-18 10:12:51',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '63',
                'pid' => '62',
                'path' => 'areas',
                'class_name' => null,
                'path_id' => '/0/62/63/',
                'icon' => null,
                'sort' => '33',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '40',
                'created_at' => '2019-06-18 10:14:02',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '66',
                'pid' => '62',
                'path' => 'areas/create',
                'class_name' => null,
                'path_id' => '/0/62/66/',
                'icon' => null,
                'sort' => '35',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '40',
                'created_at' => '2019-06-18 10:19:53',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '67',
                'pid' => '10',
                'path' => '/email-template',
                'class_name' => '#',
                'path_id' => '/0/10/67/',
                'icon' => null,
                'sort' => '77',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '58',
                'created_at' => '2019-06-22 02:31:32',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '68',
                'pid' => '62',
                'path' => 'construction',
                'class_name' => null,
                'path_id' => '/0/62/68/',
                'icon' => null,
                'sort' => '41',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '59',
                'created_at' => '2019-06-26 05:00:05',
                'updated_at' => '2019-07-26 08:57:56',
            ],

            [
                'id' => '69',
                'pid' => '62',
                'path' => 'construction/create',
                'class_name' => null,
                'path_id' => '/0/62/69/',
                'icon' => null,
                'sort' => '43',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '59',
                'created_at' => '2019-06-26 05:01:28',
                'updated_at' => '2019-07-26 08:57:56',
            ],

            [
                'id' => '70',
                'pid' => '46',
                'path' => 'contracts/create',
                'class_name' => null,
                'path_id' => '/0/46/70/',
                'icon' => null,
                'sort' => '21',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '13',
                'created_at' => '2019-06-26 08:55:57',
                'updated_at' => '2019-07-16 01:51:51',
            ],

            [
                'id' => '71',
                'pid' => '0',
                'path' => '/procedure',
                'class_name' => null,
                'path_id' => '/0/71/',
                'icon' => 'mdi mdi-help-circle',
                'sort' => '4',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '2',
                'created_at' => '2019-06-28 08:39:53',
                'updated_at' => '2019-07-16 09:37:58',
            ],

            [
                'id' => '73',
                'pid' => '10',
                'path' => '/excel-template',
                'class_name' => null,
                'path_id' => '/0/10/73/',
                'icon' => null,
                'sort' => '79',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '61',
                'created_at' => '2019-07-03 03:26:59',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '75',
                'pid' => '74',
                'path' => '/admin/product-class',
                'class_name' => null,
                'path_id' => '/0/74/75/',
                'icon' => null,
                'sort' => '47',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '56',
                'created_at' => '2019-07-06 08:59:24',
                'updated_at' => '2019-07-16 09:37:58',
            ],

            [
                'id' => '76',
                'pid' => '10',
                'path' => '/admin/item-class',
                'class_name' => null,
                'path_id' => '/0/10/76/',
                'icon' => null,
                'sort' => '61',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '52',
                'created_at' => '2019-07-06 09:02:44',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '77',
                'pid' => '0',
                'path' => '#',
                'class_name' => null,
                'path_id' => '/0/77/',
                'icon' => 'mdi mdi-drag',
                'sort' => '26',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '60',
                'created_at' => '2019-07-16 03:17:10',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '78',
                'pid' => '77',
                'path' => 'factory_product',
                'class_name' => null,
                'path_id' => '/0/77/80/',
                'icon' => null,
                'sort' => '27',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '60',
                'created_at' => '2019-07-16 03:18:10',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '79',
                'pid' => '77',
                'path' => 'factory_product/external',
                'class_name' => null,
                'path_id' => '/0/77/80/',
                'icon' => null,
                'sort' => '0',
                'level' => '0',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => null,
                'allow_type' => null,
                'module_id' => '60',
                'created_at' => '2019-07-16 03:18:59',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '80',
                'pid' => '77',
                'path' => 'factory_product/external',
                'class_name' => null,
                'path_id' => '/0/77/80/',
                'icon' => null,
                'sort' => '29',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '60',
                'created_at' => '2019-07-16 03:21:13',
                'updated_at' => '2019-07-26 08:57:55',
            ],

            [
                'id' => '81',
                'pid' => '10',
                'path' => '/admin/matrix-value',
                'class_name' => null,
                'path_id' => '/0/10/86/',
                'icon' => null,
                'sort' => '49',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '54',
                'created_at' => '2019-07-20 02:23:53',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '82',
                'pid' => '10',
                'path' => '/admin/matrix-type',
                'class_name' => null,
                'path_id' => '/0/10/86/',
                'icon' => null,
                'sort' => '51',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '53',
                'created_at' => '2019-07-20 02:24:38',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '83',
                'pid' => '10',
                'path' => '/admin/product-class',
                'class_name' => null,
                'path_id' => '/0/10/86/',
                'icon' => null,
                'sort' => '53',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '56',
                'created_at' => '2019-07-20 02:26:37',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '84',
                'pid' => '10',
                'path' => '/admin/item-price',
                'class_name' => null,
                'path_id' => '/0/10/86/',
                'icon' => null,
                'sort' => '55',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '51',
                'created_at' => '2019-07-20 02:36:18',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '85',
                'pid' => '10',
                'path' => '/admin/items',
                'class_name' => null,
                'path_id' => '/0/10/86/',
                'icon' => null,
                'sort' => '57',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '52',
                'created_at' => '2019-07-20 02:38:44',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '86',
                'pid' => '10',
                'path' => '/admin/price-pattern',
                'class_name' => null,
                'path_id' => '/0/10/86/',
                'icon' => null,
                'sort' => '59',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '55',
                'created_at' => '2019-07-20 03:36:10',
                'updated_at' => '2019-07-26 08:57:57',
            ],

            [
                'id' => '87',
                'pid' => '10',
                'path' => 'admin/currency',
                'class_name' => null,
                'path_id' => '/0/10/87/',
                'icon' => null,
                'sort' => '47',
                'level' => '2',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '62',
                'created_at' => '2019-07-23 08:28:29',
                'updated_at' => '2019-07-26 08:57:56',
            ],

            [
                'id' => '88',
                'pid' => '0',
                'path' => '/main-list',
                'class_name' => null,
                'path_id' => '/0/88/',
                'icon' => null,
                'sort' => '24',
                'level' => '1',
                'description' => null,
                'shortcode' => null,
                'status_id' => '25',
                'group_id' => '3',
                'allow_type' => null,
                'module_id' => '63',
                'created_at' => '2019-07-26 08:57:40',
                'updated_at' => '2019-07-26 08:57:55',
            ],

        ];

        foreach($data as $item) 
        {
            $this->saveData("menus", $item);
        }
    }

}