<?php

use Illuminate\Database\Seeder;
use Elimuswift\DbExporter\SeederHelper;

class RoleModuleDatabaseSeeder extends Seeder 
{

	use SeederHelper;
	
    public function run()
    {
        
        $data = [
            
            [
                'module_id' => '1',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => null,
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '1',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-11 03:36:49',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '1',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:22',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '1',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '5',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-11 03:34:57',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '5',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-11 03:36:50',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '5',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:22',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '5',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '6',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-11 03:34:57',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '6',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-11 03:36:50',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '6',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:22',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '6',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '7',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-11 03:34:58',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '7',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-11 03:36:50',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '7',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:22',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '7',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '9',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:39:25',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '9',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-23 04:50:44',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '9',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:23',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '9',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '11',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-02 11:13:36',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '11',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-30 03:36:44',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '11',
                'role_id' => '8',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '12',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:39:25',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '12',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-23 04:50:44',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '12',
                'role_id' => '3',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:23',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '12',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '13',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:39:25',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '13',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-23 04:50:44',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '13',
                'role_id' => '3',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:23',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '13',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '14',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:39:25',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '14',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-23 04:50:44',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '14',
                'role_id' => '3',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-22 11:40:23',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '14',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '16',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-23 08:25:17',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '16',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-05-02 09:19:59',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '16',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-04-23 09:17:01',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '16',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '17',
                'role_id' => '1',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-27 02:59:51',
                'updated_at' => '2019-04-27 02:59:51',
            ],

            [
                'module_id' => '17',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-05-02 09:19:59',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '17',
                'role_id' => '3',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-04-23 09:17:01',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '17',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '18',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-05-02 09:19:59',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '18',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-02 10:51:33',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '18',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:08',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '20',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-30 03:36:16',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '20',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-30 03:36:44',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '20',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:09',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '30',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-30 03:36:16',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '30',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-05-30 03:36:44',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '30',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:09',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '40',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-18 11:56:10',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '40',
                'role_id' => '3',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '50',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '51',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '52',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '53',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '54',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '55',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '56',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:28',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '57',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:32:29',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '40',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:06',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '50',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:06',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '51',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:06',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '52',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:06',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '53',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:06',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '54',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:06',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '55',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:07',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '56',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:07',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '57',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-20 10:33:07',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '58',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:02:38',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '59',
                'role_id' => '3',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:02:39',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '1',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '5',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '6',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '7',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '9',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '11',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '12',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '13',
                'role_id' => '4',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:55',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '14',
                'role_id' => '4',
                'view' => '1',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '16',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '17',
                'role_id' => '4',
                'view' => '1',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '18',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '20',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '30',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '40',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '50',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '51',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '52',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '53',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '54',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '55',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:56',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '56',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:57',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '57',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:57',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '58',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:57',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '59',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-06-27 05:03:57',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '60',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-11 07:51:15',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '61',
                'role_id' => '3',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-11 07:51:16',
                'updated_at' => '2019-07-21 08:28:31',
            ],

            [
                'module_id' => '58',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 07:58:53',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '59',
                'role_id' => '2',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-21 07:58:53',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '60',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 07:58:53',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '61',
                'role_id' => '2',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 07:58:53',
                'updated_at' => '2019-07-21 07:58:53',
            ],

            [
                'module_id' => '50',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '51',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '52',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '53',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '54',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '55',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '56',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '57',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '58',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '59',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '60',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '61',
                'role_id' => '8',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '62',
                'role_id' => '8',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-21 15:19:20',
                'updated_at' => '2019-07-21 15:19:20',
            ],

            [
                'module_id' => '60',
                'role_id' => '4',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:21:48',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '61',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:21:48',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '62',
                'role_id' => '4',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:21:48',
                'updated_at' => '2019-07-22 00:21:48',
            ],

            [
                'module_id' => '1',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '5',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '6',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '7',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '9',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '11',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '12',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '13',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '14',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '16',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '17',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '18',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '20',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '30',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '40',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '50',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '51',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '52',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '53',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '54',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '55',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '56',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '57',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '58',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '59',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '60',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '61',
                'role_id' => '5',
                'view' => '0',
                'add' => '0',
                'update' => '0',
                'delete' => '0',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

            [
                'module_id' => '62',
                'role_id' => '5',
                'view' => '1',
                'add' => '1',
                'update' => '1',
                'delete' => '1',
                'all' => '0',
                'created_at' => '2019-07-22 00:24:05',
                'updated_at' => '2019-07-22 00:26:51',
            ],

        ];

        foreach($data as $item) 
        {
            $this->saveData("role_module", $item);
        }
    }

}